<?php 

 //{{block class="Magento\Framework\View\Element\Template" name="formblock" template="Magento_Theme::laserform.phtml"}} 

ini_set('max_input_vars', 10000);
if(isset($_POST["submitnow"]) && !empty($_POST["fromname"]) ){
  print_r($_POST);  

   						$fromname = $_POST["fromname"];
                       // $fromemail = $_POST["fromemail"];
                       // $replytoname = $_POST["replytoname"];
                       // $replytoemail = $_POST["replytoemail"];
                        $to = $_POST["to"];
                       // $subject = $_POST["subject"];
                        $message1 = $_POST["message"];

    //php validation, exit outputting json string
	// CREATE FULL FIELDS (NAME + EMAIL)
	$fromFull 	=   'Metalcuttosize <admin@metalcuttosize.co.uk> ';
	//$replytoFull 	=   'Metalcuttosize <info@metalcuttosize.co.uk> ';

	//$to = "admin@metalcuttosize.co.uk";
  $to = "testphp24@gmail.com";

    $subject        =  "Laser cutting - request";
	//$mgs = "".$message;
	$message        = "<p>Hello admin ,\n\r </p>";
	$message        .= "<p>Name : ".$fromname."\n </p>";
	$message        .= "<p>Email : ".$to."\n </p>";
	//$message        .= "Message : ".filter_var($mgs, FILTER_SANITIZE_STRING); //capture message
	$message        .= "<p>Message : ".$message1."\n </p>"; //capture message

    $attachments = $_FILES['my_files'];
    
    $file_count = count($attachments['name']); //count total files attached
    $boundary = md5("shopinson.com"); 
    
    //construct a message body to be sent to recipient
    //$message_body =  "------------------------------\n";
    
    //$message_body =  "$message\n";
	
	$message_body = '<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Simple Transactional Email</title>
    <style>
      /* -------------------------------------
          GLOBAL RESETS
      ------------------------------------- */
      
      /*All the styling goes here*/
      
      img {
        border: none;
        -ms-interpolation-mode: bicubic;
        max-width: 100%; 
      }

      body {
        background-color: #f6f6f6;
        font-family: sans-serif;
        -webkit-font-smoothing: antialiased;
        font-size: 14px;
        line-height: 1.4;
        margin: 0;
        padding: 0;
        -ms-text-size-adjust: 100%;
        -webkit-text-size-adjust: 100%; 
      }

      table {
        border-collapse: separate;
        mso-table-lspace: 0pt;
        mso-table-rspace: 0pt;
        width: 100%; }
        table td {
          font-family: sans-serif;
          font-size: 14px;
          vertical-align: top; 
      }

      /* -------------------------------------
          BODY & CONTAINER
      ------------------------------------- */

      .body {
        background-color: #f6f6f6;
        width: 100%; 
      }

      /* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
      .container {
        display: block;
        margin: 0 auto !important;
        /* makes it centered */
        max-width: 580px;
        padding: 10px;
        width: 580px; 
      }

      /* This should also be a block element, so that it will fill 100% of the .container */
      .content {
        box-sizing: border-box;
        display: block;
        margin: 0 auto;
        max-width: 580px;
        padding: 10px; 
      }

      /* -------------------------------------
          HEADER, FOOTER, MAIN
      ------------------------------------- */
      .main {
        background: #ffffff;
        border-radius: 3px;
        width: 100%; 
      }

      .wrapper {
        box-sizing: border-box;
        padding: 20px; 
      }

      .content-block {
        padding-bottom: 10px;
        padding-top: 10px;
      }

      .footer {
        clear: both;
        margin-top: 10px;
        text-align: center;
        width: 100%; 
      }
        .footer td,
        .footer p,
        .footer span,
        .footer a {
          color: #999999;
          font-size: 12px;
          text-align: center; 
      }

      /* -------------------------------------
          TYPOGRAPHY
      ------------------------------------- */
      h1,
      h2,
      h3,
      h4 {
        color: #000000;
        font-family: sans-serif;
        font-weight: 400;
        line-height: 1.4;
        margin: 0;
        margin-bottom: 30px; 
      }

      h1 {
        font-size: 35px;
        font-weight: 300;
        text-align: center;
        text-transform: capitalize; 
      }

      p,
      ul,
      ol {
        font-family: sans-serif;
        font-size: 14px;
        font-weight: normal;
        margin: 0;
        margin-bottom: 15px; 
      }
        p li,
        ul li,
        ol li {
          list-style-position: inside;
          margin-left: 5px; 
      }

      a {
        color: #3498db;
        text-decoration: underline; 
      }

      /* -------------------------------------
          BUTTONS
      ------------------------------------- */
      .btn {
        box-sizing: border-box;
        width: 100%; }
        .btn > tbody > tr > td {
          padding-bottom: 15px; }
        .btn table {
          width: auto; 
      }
        .btn table td {
          background-color: #ffffff;
          border-radius: 5px;
          text-align: center; 
      }
        .btn a {
          background-color: #ffffff;
          border: solid 1px #3498db;
          border-radius: 5px;
          box-sizing: border-box;
          color: #3498db;
          cursor: pointer;
          display: inline-block;
          font-size: 14px;
          font-weight: bold;
          margin: 0;
          padding: 12px 25px;
          text-decoration: none;
          text-transform: capitalize; 
      }

      .btn-primary table td {
        background-color: #3498db; 
      }

      .btn-primary a {
        background-color: #3498db;
        border-color: #3498db;
        color: #ffffff; 
      }

      /* -------------------------------------
          OTHER STYLES THAT MIGHT BE USEFUL
      ------------------------------------- */
      .last {
        margin-bottom: 0; 
      }

      .first {
        margin-top: 0; 
      }

      .align-center {
        text-align: center; 
      }

      .align-right {
        text-align: right; 
      }

      .align-left {
        text-align: left; 
      }

      .clear {
        clear: both; 
      }

      .mt0 {
        margin-top: 0; 
      }

      .mb0 {
        margin-bottom: 0; 
      }

      .preheader {
        color: transparent;
        display: none;
        height: 0;
        max-height: 0;
        max-width: 0;
        opacity: 0;
        overflow: hidden;
        mso-hide: all;
        visibility: hidden;
        width: 0; 
      }

      .powered-by a {
        text-decoration: none; 
      }

      hr {
        border: 0;
        border-bottom: 1px solid #f6f6f6;
        margin: 20px 0; 
      }

      /* -------------------------------------
          RESPONSIVE AND MOBILE FRIENDLY STYLES
      ------------------------------------- */
      @media only screen and (max-width: 620px) {
        table[class=body] h1 {
          font-size: 28px !important;
          margin-bottom: 10px !important; 
        }
        table[class=body] p,
        table[class=body] ul,
        table[class=body] ol,
        table[class=body] td,
        table[class=body] span,
        table[class=body] a {
          font-size: 16px !important; 
        }
        table[class=body] .wrapper,
        table[class=body] .article {
          padding: 10px !important; 
        }
        table[class=body] .content {
          padding: 0 !important; 
        }
        table[class=body] .container {
          padding: 0 !important;
          width: 100% !important; 
        }
        table[class=body] .main {
          border-left-width: 0 !important;
          border-radius: 0 !important;
          border-right-width: 0 !important; 
        }
        table[class=body] .btn table {
          width: 100% !important; 
        }
        table[class=body] .btn a {
          width: 100% !important; 
        }
        table[class=body] .img-responsive {
          height: auto !important;
          max-width: 100% !important;
          width: auto !important; 
        }
      }

      /* -------------------------------------
          PRESERVE THESE STYLES IN THE HEAD
      ------------------------------------- */
      @media all {
        .ExternalClass {
          width: 100%; 
        }
        .ExternalClass,
        .ExternalClass p,
        .ExternalClass span,
        .ExternalClass font,
        .ExternalClass td,
        .ExternalClass div {
          line-height: 100%; 
        }
        .apple-link a {
          color: inherit !important;
          font-family: inherit !important;
          font-size: inherit !important;
          font-weight: inherit !important;
          line-height: inherit !important;
          text-decoration: none !important; 
        }
        #MessageViewBody a {
          color: inherit;
          text-decoration: none;
          font-size: inherit;
          font-family: inherit;
          font-weight: inherit;
          line-height: inherit;
        }
        .btn-primary table td:hover {
          background-color: #34495e !important; 
        }
        .btn-primary a:hover {
          background-color: #34495e !important;
          border-color: #34495e !important; 
        } 
      }

    </style>
  </head>
  <body class="">
    <span class="preheader">This is preheader text. Some clients will show this text as a preview.</span>
    <table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">
      <tr>
        <td>&nbsp;</td>
        <td class="container">
          <div class="content">

            <!-- START CENTERED WHITE CONTAINER -->
            <table role="presentation" class="main">

              <!-- START MAIN CONTENT AREA -->
              <tr>
                <td class="wrapper">
                  <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                    <tr>
                      <td>'.$message.'</td>
                    </tr>
                  </table>
                </td>
              </tr>

            <!-- END MAIN CONTENT AREA -->
            </table>
            <!-- END CENTERED WHITE CONTAINER -->

            <!-- START FOOTER -->
            <div class="footer">
              <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                <tr>
                  <td class="content-block">
                    <span class="apple-link">Unit D, Beverley Road, Southall, Middx, UB2 4EF</span>
                  </td>
                </tr>
                <tr>
                  <td class="content-block powered-by">
                   Metalcuttosize.co.uk © 2020. All Rights Reserved
                  </td>
                </tr>
              </table>
            </div>
            <!-- END FOOTER -->

          </div>
        </td>
        <td>&nbsp;</td>
      </tr>
    </table>
  </body>
</html>';

    
    if($file_count > 0){ //if attachment exists
        //header
        $headers = "MIME-Version: 1.0\r\n";
        $headers  = "From: ".$fromFull . "\r\n";
      //  $headers .= "Reply-To: ".$replytoFull . "\r\n";
    	// $headers .= "To: Mary <mary@example.com>, Kelly <kelly@example.com>" . "\r\n";
		// $headers .= "Cc: sendacopy@here.com" . "\r\n";
		// $headers .= "Bcc: sendablindcopy@here.com" . "\r\n";
		// $headers .= "X-Sender: testsite < mail@testsite.com >" . "\r\n";
		// $headers .= "Return-Path: " . $fromFull . "\r\n";
		// $headers .= "Content-Type: text/html; charset=ISO-8859-1" . "\r\n";
	$headers .= "X-Mailer: PHP/" . phpversion() . "\r\n";
	$headers .= "X-Priority: 1" . "\r\n";
	$headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";

        $headers .= "Content-Type: multipart/mixed; \r\n\r\n"; 
        
        //message text
        $body = "--$boundary\r\n";
        $body .= "Content-Type: text/plain; charset=ISO-8859-1\r\n";
        $body .= "Content-Transfer-Encoding: base64\r\n\r\n"; 
        $body .= chunk_split(base64_encode($message_body)); 

        //attachments
        for ($x = 0; $x < $file_count; $x++){       
            if(!empty($attachments['name'][$x])){
                
                if($attachments['error'][$x]>0) //exit script and output error if we encounter any
                {
                    $mymsg = array( 
                    1=>"The uploaded file exceeds the upload_max_filesize directive in php.ini", 
                    2=>"The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form", 
                    3=>"The uploaded file was only partially uploaded", 
                    4=>"No file was uploaded", 
                    6=>"Missing a temporary folder" ); 
                   // print  $mymsg[$attachments['error'][$x]]; 
					echo "<script>
					alert('".$mymsg[$attachments['error'][$x]]."');
				</script>";
                    //exit;
                }
                

                //get file info
                $file_name = $attachments['name'][$x];
                $file_size = $attachments['size'][$x];
                $file_type = $attachments['type'][$x];
                
                //read file 
                $handle = fopen($attachments['tmp_name'][$x], "r");
                $content = fread($handle, $file_size);
                fclose($handle);
                $encoded_content = chunk_split(base64_encode($content)); //split into smaller chunks (RFC 2045)
                
                $body .= "--$boundary\r\n";
                $body .="Content-Type: $file_type; name=".$file_name."\r\n";
                $body .="Content-Disposition: attachment; filename=".$file_name."\r\n";
                $body .="Content-Transfer-Encoding: base64\r\n";
                $body .="X-Attachment-Id: ".rand(1000,99999)."\r\n\r\n"; 
                $body .= $encoded_content; 
            }
        }

    }else{ //send plain email otherwise
	// FULL HEADER
	$headers  = "From: ".$fromFull . "\r\n";
	$headers .= "Reply-To: ".$replytoFull . "\r\n";
	// $headers .= "To: Mary <mary@example.com>, Kelly <kelly@example.com>" . "\r\n";
	// $headers .= "Cc: sendacopy@here.com" . "\r\n";
	// $headers .= "Bcc: sendablindcopy@here.com" . "\r\n";
	// $headers .= "X-Sender: testsite < mail@testsite.com >" . "\r\n";
	// $headers .= "Return-Path: " . $fromFull . "\r\n";
	// $headers .= "Content-Type: text/html; charset=ISO-8859-1" . "\r\n";
	$headers .= "X-Mailer: PHP/" . phpversion() . "\r\n";
	$headers .= "X-Priority: 1" . "\r\n";
	$headers .= "MIME-Version: 1.0" . "\r\n";
	$headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";

        $body = $message_body;
    }
    $sentMail = mail('testphp24@gmail.com', $subject, $body, $headers);

   // $sentMail = mail($to, $subject, $body, $headers);
    if($sentMail) //output success or failure messages
    { //echo "mail sent successfully";  
     	echo "<script>
					alert('Thank you for your email');//location.reload();
          setTimeout(function(){ window.location.href = 'https://m2.metalcuttosize.co.uk/laser-cutting'; }, 3000);
			document.getElementById('laserfrom').reset();
          document.getElementById('sucess').html('Thank you for your email');

				</script>"; //  header('Location: '.$_SERVER['REQUEST_URI']); //setTimeout(function(){". header('Location: https://m2.metalcuttosize.co.uk/laser-cutting') ."}, 5000);

			//	header('Location: https://m2.metalcuttosize.co.uk/laser-cutting');
				//setTimeout(function(){ header('Location: https://m2.metalcuttosize.co.uk/laser-cutting'); }, 3000);
//exit;
  // lets pretend nothing was posted

        //print 'Thank you for your email';
        //exit;
    }else{ //echo "Could not send mail";
		echo "<script>
					alert('Could not send mail! Please check your PHP mail configuration.');
				</script>";  
       // print 'Could not send mail! Please check your PHP mail configuration.';  
        //exit;
    }
/*
    $_POST = array();    //
    unset($_POST["submitnow"]);
    unset($_POST["fromname"]);
    print_r($_POST);   unset($_POST);*/


   // exit;
}

?>

<div class="form-style-3">
  <div id="sucess"> </div>
<form role="form"  method="post" id="laserfrom" enctype="multipart/form-data">
<label for=""><span>Name :<span class="required">*</span></span>
<input class="form-control" id="inputdefault" type="text" name="fromname"  required /></label>

<label for=""><span>Email:<span class="required">*</span></span>
<input class="form-control" id="inputdefault" type="text" name="to" required /></label>

<label for=""><span>Message:<span class="required">*</span></span>
<textarea rows="7" cols="70" name="message" maxlength="10000" placeholder="write messages here....."></textarea></label>

<label for=""><span>Upload image:<span class="required">*</span></span>
<input class="form-control" id="inputdefault" type="file" name="my_files[]" value="" accept="image/*" size="23"></label>

<label><span></span> <input id="inputdefault" type="submit" value="Send Now" name="submitnow"  
      >
</label>
<!--   data-sitekey="6Le0edsZAAAAAM9Q9DjiG9M9XTp901O6hco_sv15" 
        data-callback='onSubmit' 
        data-action='submit' class="btn btn-primary form-control g-recaptcha" -->
</form>
</div>
 <script src="https://www.google.com/recaptcha/api.js"></script>

   <script>
   function onSubmit(token) {
     document.getElementById("laserfrom").submit();
   }
 </script>
<style type="text/css">
.form-style-3{
	max-width: 50%;
}
.form-style-3 label{
	display:block;
	margin-bottom: 10px;
}
.form-style-3 label > span{
	float: left;
	width: 100px;
	font-weight: bold;
	font-size: 13px;
}
.form-style-3 fieldset{
	
	margin: 0px 0px 10px 0px;
	border: 1px solid #FFD2D2;
	padding: 20px;
	
}
.form-style-3 fieldset legend{
	
	padding: 0px 8px 3px 8px;
	
	font-weight: normal;
	font-size: 12px;
}
.form-style-3 textarea{
	width:250px;
	height:100px;
}
.form-style-3 input[type=text],
.form-style-3 input[type=date],
.form-style-3 input[type=datetime],
.form-style-3 input[type=number],
.form-style-3 input[type=search],
.form-style-3 input[type=time],
.form-style-3 input[type=url],
.form-style-3 input[type=email],
.form-style-3 select, 
.form-style-3 textarea{
	
	outline: none;
	padding: 5px 8px 5px 8px;
	
	width:50%;
}
.required{
	color:red;
	font-weight:normal;
}

@media screen and (max-width: 767px) {
.form-style-3 {
    max-width: 100%;
}

}
</style>