<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <div class="block pad-main-product">
        <?php if ($title): ?>
            <div class="block-title-main">
                <h2 role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></h2>
                <div class="title-border"></div>
            </div>
        <?php endif ?>
        <div style="margin-bottom: 0;float: left;width:100%;" class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
            <div class="block-content">
                <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                    <ol style="margin: 0;" class="product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                        <?php $iterator = 1; ?>
                        <?php foreach ($items as $_item): ?>
                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                            <div class="product-item-info type3">
                                <div class="product-img-block">
                                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                        <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                        <div class="pro-overlay"></div>
                                    </a>
 <a class="weltpixel-quickview weltpixel_quickview_button_v2"  href="<?php  echo $_item->getProductUrl()  ?>"><span class="action primary tocart"><em class="porto-icon-eye"></em><span>Add to Cart</span></span></a>
                                </div>

                                <div class="product-item-details">
                                    <strong class="product-item-name">
                                        <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                           href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                           class="product-item-link">
                                            <?php echo $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>
                                    <?php
                                   // echo $block->getProductPriceHtml($_item, $type);
                                    ?>

                                   
                                </div>

                            </div>
                            <?php echo($iterator == count($items) + 1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                    </ol>
                </div>
                <?php echo $block->getPagerHtml() ?>
            </div>
        </div>
    </div>
<?php endif; ?>
